// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/glean/ask": {
            "get": {
                "description": "Submits a query against a completed Gleaner indexing task and streams the grounded answer token-by-token through Server-Sent Events (SSE).",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "Gleaner"
                ],
                "summary": "Ask a question against an indexed document",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The task_id of the completed indexing task",
                        "name": "document_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Question to answer from the indexed document",
                        "name": "query",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "SSE Stream",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Missing parameters",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Indexed document not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Document indexing not completed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/glean/index": {
            "post": {
                "description": "Streams a document to S3-compatible storage, chunks it, embeds it through FastEmbed, and builds a FAISS index in the background. Identical documents reuse completed or in-flight indexes.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Gleaner"
                ],
                "summary": "Upload document for vector indexing",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Document to index (.txt, .pdf, .docx)",
                        "name": "document",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Document queued for indexing",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Missing document file",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "200": {
                        "description": "Cached index reused successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns the current status of the Lexos Gateway.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Core"
                ],
                "summary": "Check API health",
                "responses": {
                    "200": {
                        "description": "API is healthy",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/summarize": {
            "post": {
                "description": "Uploads text or a document (.txt, .pdf, .docx) to the asynchronous Qwen3 Map-Reduce pipeline. Identical content reuses completed or in-flight work when the summary style matches.",
                "consumes": [
                    "multipart/form-data",
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Distiller"
                ],
                "summary": "Submit a document for AI summarization",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Document to summarize (if using multipart)",
                        "name": "document",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Summary style (bullet_points, short_paragraph, executive)",
                        "name": "style",
                        "in": "formData"
                    },
                    {
                        "description": "JSON payload (if using application/json)",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/handlers.SummarizeRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Task queued successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "200": {
                        "description": "Cached task reused successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/task/{id}": {
            "get": {
                "description": "Fetches the current processing state and result URL for a given task ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Core"
                ],
                "summary": "Get the status of an async task",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Task state details",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Task not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/task/{id}/result": {
            "get": {
                "description": "Securely proxies the resulting JSON artifact from private S3-compatible object storage.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Core"
                ],
                "summary": "Download task result",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The raw JSON result",
                        "schema": {}
                    },
                    "404": {
                        "description": "Result not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/transcribe": {
            "post": {
                "description": "Uploads an audio file to S3-compatible object storage and queues it for transcription using Faster-Whisper. Identical inputs reuse completed or in-flight processing.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Scriber"
                ],
                "summary": "Submit audio for transcription",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Audio file to transcribe",
                        "name": "audio",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Task queued successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Missing audio file",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "200": {
                        "description": "Cached task reused successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.SummarizeRequest": {
            "type": "object",
            "properties": {
                "document_text": {
                    "type": "string"
                },
                "style": {
                    "type": "string"
                }
            }
        }
    },
    "schemes": {{ marshal .Schemes }}
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Lexos API",
	Description:      "The cloud-native API gateway for the Lexos AI document processing engine.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
